### ISSUE TITLE
l.js busts itself, and the vm.

### ISSUE THREAD

**Issue by IngwiePhoenix** [malko/l.js#13]
I am embedding the l.min.js script directly into the document by using PHP. The script is stored in an in-memory cache and embedded into the page, then served. At least, that is what I wanted to do. But it seems that `gEval` is being called over, and over, and over - untill it causes an error:

    Uncaught RangeError: Maximum call stack size exceeded

Could you look into this? Thus far, l.js seems to be the smallest loader that supports "bundles" (i.e. combining a few things into one name)

Kind regards!

**Comment by malko** [comment]
Hi sorry for the late answer?
Can you please provide code sample that reproduce the problem.

**Comment by IngwiePhoenix** [comment]
Take the l.js source, and paste it straight into a script tag, like <script>yaddayadda</script> and just run that. That reproduces the error.

**Comment by malko** [comment]
Ok i now understand what you mean.
This is not the way l.js was intended to be used as it will parse it's inclusion tag for content to eval. You can remove the last expression ```script && gEval(script);``` at the end of the file and it should work.
Or for the minified version ```f&&i(f)```

I plan to change the way the tag is evaluated in a future version (coming soon i hope) but the insertion tag content will still be evaluated. I'll try to see if it will be doable at minimal cost to avoid self evaluation at that time.

Hope this will solve your problem keep me informed.

**Comment by IngwiePhoenix** [comment]
Sadly this solution is not going to work for me. In my scenario I am using PHP to insert the code - either from a redis cache or from the file itself if it isnt found in the cache. So modifying the content is not really an option, since I am going off the official versions using NPM, Bower and the like.

Please let me know if you found a way to work this out :)

Something that would spring to my mind would be to check the tag the script is executed in, if it ever even included l.js externally - and if not, skip the remaining stuff and turn straight to the awesome.

Kind regards,
Ingwie

**Comment by ivanrey** [comment]
One quick solution is to fork the repository, make the one line change and load your content from your own repository. Both NPM and bower allow you to do that very easily.

**Comment by malko** [comment]
Finally closed by version 0.1.1 plus no more eval in the code
