### ISSUE TITLE
fail case

### ISSUE THREAD

**Issue by djangosdk** [malko/l.js#14]
Hi,
Incase of any failed resources (dont exist, path incorrect), how can i capture that ? I only see load function.
is there a fail function so i can do something like ``` .load().fail()```

I want to use it with aliases method ..

**Comment by malko** [comment]
Hi, sorry for the late answer but it was holyday time for me ;)
This is not possible at this time, it should be doable at minimal cost, but will only work for browser supporting script.onerror (which mean all recent browsers). 
Will try to implement this as soon as i get a little free time as i'm working on another lib at this time.
Thanks for your interest and report.

**Comment by malko** [comment]
In the mean time you can use a fallback script. see https://github.com/malko/l.js#define-a-fallback-url

**Comment by djangosdk** [comment]
@malko 
My aim is display a log where it could be shown which resources were loaded successfully (show success icon) and which did not (show error icon).
Is it possible to load images,fonts and sounds alongwith JS and CSS files ?

**Comment by malko** [comment]
this is not and won't be in the scope of ljs.

**Comment by malko** [comment]
Work will be done for issue #15 i close this one.
