### ISSUE TITLE
progress Handling, compatibility with Pace.js 

### ISSUE THREAD

**Issue by djangosdk** [malko/l.js#16]
Hi,
Is it possible to get progress of loaded content ?
I am trying to use [pace.js](http://github.hubspot.com/pace/docs/welcome/) with l.js but it does not work. 

I have lots of assets and I need to display progress as just showing busy-spinners dont give information to users on how much is loaded and how much remaining.
Something like 
```
ljs
.addAliases(aliases)
 .load('all-assets',function(){ /* your callback here */}) 
 .onProgress( function(value,total ){ /* could display progress here in percentage */}) 
```

**Comment by malko** [comment]
l.js don't check any progress of the loading resources. I don't know about pace.js i'll have a look into it and come back to you as soon as possible

**Comment by malko** [comment]
after more invesigation on the subject i think it's more to pace.js to be able to detect new resources insertion in the dom. Adding a progress event management in l.js will kill its purpose (be the smaller it can be without doing extra things). So for now i won't make any modification in that way and close the issue at won't fix.

Thanks for your report anyway
