### ISSUE TITLE
Uncaught TypeError: appendElmt is not a function

### ISSUE THREAD

**Issue by ivanrey** [malko/l.js#17]
It seems that after switching to appendElmt instead of gEval there is an scope issue.

Since the var .... appendElmnt is inside an if the variable isn't actually available at the return line (149) thus causing an error in the console>

Uncaught TypeError: appendElmt is not a function

There are several ways to fix it. I just sent a Pull Request with one, but feel free to dismiss it and change it to your own preference.

**Comment by ivanrey** [comment]
Pull Request #18

**Comment by malko** [comment]
Hi @ivanrey thanks for report, can you please provide me with a reproductible exemple and precise me the environment (os / browser).
Thanks for your involvment

**Comment by malko** [comment]
hi @ivanrey i finally have reproduce the bug it seems to happen when you include twice l.js like this: ```<script src="l.js>some code here</script>```.
Anyway I made a fix for this in the newer version and add a new onError method check the readme.
