### ISSUE TITLE
Apply doesn't work to user arguments array ?

### ISSUE THREAD

**Issue by ajira86** [malko/l.js#19]
Hello,

I tried to load multiple css files one by one with a table but the apply doesn't seams to work with a case like thie:

```
cssUrls = [ "http://../first.css", "http://../second.css" ];
ljs.load.apply(null, cssUrls);
```

I got this error with Firefox:

```
TypeError: this.loadcss is not a function
...pply(this,t)}return t.match(/\.css\b/)?this.loadcss(t,e):this.loadjs(t,e)},y={},...
-------------------------------------------^
```

I have the same kind of error with JavaScript files as urls. Is there an another way to load files one by one from an array ? (v0.1.1)

**Comment by ivanrey** [comment]
load takes an array argument. Just use

 ljs.load(cssUrls);

**Comment by ajira86** [comment]
Yes but in this case it will load all element in parallel but I want to load one by one in reason of css dependency, so I have to do something like this:

ljs.load(cssUrls[0], cssUrls[1], ..., cssUrls[n], callback);

**Comment by malko** [comment]
have you tried a simple ```ljs.load.apply(ljs, cssUrls);```

**Comment by ajira86** [comment]
I copied the whole l.js minified at first line of my JavaScript file, so he will be loaded before its call
